--1.
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과'
ORDER BY ENTRANCE_DATE;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3.
SELECT PROFESSOR_NAME 교수이름, TRUNC(MONTHS_BETWEEN( TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'),SYSDATE  ) / 12 ) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;

 -- 이 방법도 있음~~
 --SELECT EXTRACT(YEAR FROM SYSDATE)- TO_NUMBER('19'||SUBSTR(PROFESSOR_SSN, 1, 2))
 --FROM TB_PROFESSOR;
 
--4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 4) 이름
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO ,STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) != 2005;

--날짜 다시 공부하깅 6.
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'Day') AS 요일
FROM DUAL;

--7.
SELECT EXTRACT(YEAR FROM (TO_DATE('99/10/11','RR/MM/DD'))),EXTRACT(MONTH FROM (TO_DATE('99/10/11','YY/MM/DD'))), EXTRACT(DAY FROM (TO_DATE('99/10/11','YY/MM/DD')))
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NAME;

--9.
SELECT STUDENT_NO, ROUND(AVG(POINT),1)
FROM TB_GRADE
GROUP BY STUDENT_NO
HAVING STUDENT_NO = 'A517178';


--10. 질문
SELECT DEPARTMENT_NO 학과번호, CAPACITY "학생수(명)"
FROM TB_DEPARTMENT
GROUP BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(STUDENT_NAME)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.  HAVING절과 WHERE절을 언제 쓰는지를 정확히 알아야할 것 같아
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13. 질문 ) 왜 0 은 출력이안댈까!!??? 넣는방법이모까
SELECT DEPARTMENT_NO 학과코드명, COUNT(*) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME 동일이름, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME;


--15. ㅇ-ㅇ 중간계산
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, POINT 평점
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO,1,4);


년도별 누적 평점 ROUND(AVG(POINT),1)













